/**
 * Photo variants. Photos uploaded to products/posts/stories as WebP get a small
 * sibling file generated by the server, named by swapping a marker in the file name:
 *
 *   shops/<id>/products/<uuid>~t-name.webp   (full size, <= 1600px)
 *   shops/<id>/products/<uuid>~s-name.webp   (thumbnail, <= 640px)
 *
 * The marker lives in the key, so the storefront can tell (without a lookup) which
 * images have a thumbnail. Pure string helpers: safe on the client and in node tests.
 * `~` can never come from a user file name (the upload routes replace it with "_").
 */
export const THUMB_FOLDERS = new Set(["products", "posts", "stories"]);
export const THUMB_WIDTH = 640;

const FULL_NAME = /^[0-9a-f-]{36}~t(?:-.*)?\.webp$/i;

/** True when a new upload should get a thumbnail (and therefore the marker in its key). */
export function isThumbEligible(folder: string, contentType: string) {
  return THUMB_FOLDERS.has(folder) && contentType === "image/webp";
}

/** Marker for the full-size file name, e.g. "<uuid>~t". Only used when isThumbEligible. */
export function fullSizeBaseName(uuid: string) {
  return `${uuid}~t`;
}

/** R2 key of the thumbnail for a full-size key, or null when the key has no thumbnail. */
export function thumbKeyFor(key: string): string | null {
  const slash = key.lastIndexOf("/");
  const name = key.slice(slash + 1);
  if (!FULL_NAME.test(name)) return null;
  return `${key.slice(0, slash + 1)}${name.replace(/~t(?=[-.])/, "~s")}`;
}

/** Public URL of the thumbnail for a full-size public URL, or null when there is none. */
export function thumbUrlFor(url: string): string | null {
  if (!url) return null;
  const queryAt = url.search(/[?#]/);
  const path = queryAt === -1 ? url : url.slice(0, queryAt);
  const suffix = queryAt === -1 ? "" : url.slice(queryAt);
  const slash = path.lastIndexOf("/");
  const name = path.slice(slash + 1);
  if (!FULL_NAME.test(name)) return null;
  return `${path.slice(0, slash + 1)}${name.replace(/~t(?=[-.])/, "~s")}${suffix}`;
}

const VARIANT_NAME = /^[0-9a-f-]{36}~[ts](?:-.*)?\.webp$/i;

/** True for a full-size or thumbnail file produced by the variant pipeline (already compressed, safe to serve as-is). */
export function isVariantUrl(url: string) {
  const queryAt = url.search(/[?#]/);
  const path = queryAt === -1 ? url : url.slice(0, queryAt);
  return VARIANT_NAME.test(path.slice(path.lastIndexOf("/") + 1));
}
